Diet/urls.py
from django.contrib import admin
from django.urls import path, include
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.conf.urls.static import static
from django.conf import settings


wagtail_urlpatterns = [
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('pages/', include(wagtail_urls)),
]
urlpatterns =[
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('',include('DemoDiet.urls')),
    path('',include('login.urls')),
    path('',include('base.urls')),
    path('',include('registration.urls')),
    path('',include('resources.urls')),
    path('',include('data_feed.urls')),
    # path('',include('base.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + wagtail_urlpatterns


# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('',include('DemoDiet.urls')),
#     path('',include('login.urls')),
#     path('',include('base.urls')),
#     path('',include('registration.urls')),
#     path('',include('resources.urls')),
#     path('',include('data_feed.urls')),
#     path('',include('CMSResources.urls')),
#     # path('',include('base.urls')),
# ] + wagtail_urlpatterns

base/urls.py
# from django.contrib import admin
from django.urls import path
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name='home'),
    url(r'^aboutus/', views.about, name='aboutus'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
# from django.contrib import admin
from django.urls import path
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
  
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^student_login/', views.student_login, name='student_login'),
    path('redirected/<str:username>',views.redirectd),
    url(r'^after_login/', views.after_login, name='after_login'),
    

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms  
from datetimepicker.widgets import DateTimePicker
from bootstrap_datepicker_plus import DatePickerInput
from django.contrib.auth.forms import UserCreationForm
import random
import string
from django.forms import Textarea
from registration.models import Mentor,MukhyaSevika,AnganwadiWorkersRegister,Student,SchoolCoordinator,User,NutriGardenExpert,SchoolStudentParent
class Form(UserCreationForm):
    email=forms.EmailField(required=False)
    
    def __init__(self, *args, **kwargs):
        super(Form, self).__init__(*args, **kwargs)

        for fieldname in ['first_name','last_name','username','email', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
    class Meta:
        model=User
        fields=('first_name','last_name','username','email', 'password1', 'password2')
    def save(self, commit=True):
        user= super().save(commit=False)

        user.email= self.cleaned_data['email']

        if commit:
            user.save()
            print(user)
        return user 

# class bulkreg(forms.ModelForm):  
#     class Meta:  
#         model = bulk_reg  
#         fields = ['name','email','mobile','roles','from_date','to_date']  
#         widgets = {
#             'from_date':forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
#             'to_date': forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
#         }
    

class ProjectManagerForm(forms.ModelForm):
    class Meta:
        model = ProjectManager
        fields = ('contact',)

class MentorForm(forms.ModelForm):
    uid =forms.CharField( widget=forms.TextInput(attrs={'readonly':'readonly'}),initial='MT'+''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(5)))
    class Meta:
        model = Mentor
        fields = ('birthdate','age','contact','address','education')

class SchoolCoordinatorForm(forms.ModelForm):
    class Meta:
        model = SchoolCoordinator
        fields = ('contact','schoolname','personaladdress',)

class SchoolForm(forms.ModelForm):
    class Meta:
        model = School
        fields = ('contact','name','institute',)

class StudentForm(forms.ModelForm):
    uid =forms.CharField( widget=forms.TextInput(attrs={'readonly':'readonly'}),initial='STU'+''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(5)))
    class Meta:
        model = Student
        fields = ('uid','nutrileader')

class AnganwadiWorkerForm(forms.ModelForm):
    uid =forms.CharField( widget=forms.TextInput(attrs={'readonly':'readonly'}),initial='ANW'+''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(5)))
    class Meta:
        model = AnganwadiWorkersRegister
        fields = ('contact','birthdate','age','education','occupation','annualincome','anganwadiname','anganwadiaddress','ICDSname','ICDScenteraddress','ICDScontact','profile_photo','uid')
        
class MukhyaSevikaForm(forms.ModelForm):
    uid =forms.CharField( widget=forms.TextInput(attrs={'readonly':'readonly'}),initial='MSU'+''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(5)))
    class Meta:
        model = MukhyaSevika
        fields = ('anganwadinumber','contact','birthdate','age','education','occupation','annualincome','ICDSname','ICDScenteraddress','ICDScontact','profile_photo','uid')
        widgets = {
                    'birthdate': DatePickerInput(format='%m/%d/%Y'), 
                 }
class SchoolCoordinatorForm(forms.ModelForm):
    uid =forms.CharField( widget=forms.TextInput(attrs={'readonly':'readonly'}),initial='SCU'+''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(5)))
    class Meta:
        model = SchoolCoordinator
        fields = ('contact','schoolname','personaladdress','birthdate','age','schooladdress','schoolcontact','education','occupation','annualincome','profile_photo','uid')
        widgets = {
                    'birthdate': DatePickerInput(format='%m/%d/%Y'), 
                 }

# class bulkreg(forms.ModelForm):  
#     class Meta:  
#         model = bulk_reg  
#         fields = ['name','mobile','birthdate']  
#         widgets = {
#             'birthdate':forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
#             # 'to_date': forms.DateInput(format=('%d/%m/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
#         }
# class DocumentForm(forms.Form):
#     title=forms.CharField(max_length=150, required=False)
#     docfile = forms.FileField(
#         label='Select a file',
#         help_text='max. 42 megabytes'
#     )
# 
class SchoolStudentParentForm(forms.ModelForm):
    uid =forms.CharField( widget=forms.TextInput(attrs={'readonly':'readonly'}),initial='STUP'+''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(5)))
    class Meta:
        model = SchoolStudentParent
        fields = ('contact','schoolname','personaladdress','birthdate','age','schooladdress','schoolcontact','education','occupation','annualincome','schoolcoordinatorincharge','foodhabits','profile_photo','uid')
        widgets = {
                    'birthdate': DatePickerInput(format='%m/%d/%Y'), 
                 }

class PrincipalInvestigatorsForm(forms.ModelForm):
    uid =forms.CharField( widget=forms.TextInput(attrs={'readonly':'readonly'}),initial='PI'+''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(5)))
    class Meta:
        model = PrincipalInvestigators
        fields = ['birthdate','age','contact','uid']
        widgets = {
                    'birthdate': DatePickerInput(format='%m/%d/%Y'), # default date-format %m/%d/%Y will be used
            
        }
class WebGISExpertForm(forms.ModelForm):
    uid =forms.CharField( widget=forms.TextInput(attrs={'readonly':'readonly'}),initial='WGE'+''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(5)))
    class Meta:
        model =  WebGISExpert
        fields = ['birthdate','age','contact','uid']
        widgets = {
                    'birthdate': DatePickerInput(format='%m/%d/%Y'), # default date-format %m/%d/%Y will be used
            
        }

class NutritionExpertForm(forms.ModelForm):
    uid =forms.CharField( widget=forms.TextInput(attrs={'readonly':'readonly'}),initial='NE'+''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(5)))
    class Meta:
        model =  NutritionExpert
        fields = ['birthdate','age','contact','uid']
        widgets = {
                    'birthdate': DatePickerInput(format='%m/%d/%Y'), # default date-format %m/%d/%Y will be used
            
        }

base/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'base.html')

def about(request):
    return render(request, 'about.html')

login/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from registration.forms import StudentForm,MukhyaSevikaForm,AnganwadiWorkerForm,SchoolCoordinatorForm,MentorForm,Form,MentorForm,SchoolStudentParentForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User,auth
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from tablib import Dataset
from django.http import JsonResponse
import openpyxl
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.contrib.auth.models import Group
# from DemoDiet.get_lat_lon_exif_pil import ImageMetaData
from django.http import HttpResponse
# from DemoDiet.resources import bulkResource
# import exiftool
from data_feed.forms import studentprof,anemicadolescentgirlprof,anemiclactatingmotherprof
from cryptography.fernet import Fernet
key = Fernet.generate_key()
f = Fernet(key)

def login(request):
    if request.method== "POST":
        username=request.POST['username']
        # email = request.POST['email']
        password = request.POST['password']
        # du = user.username
        # passwordChosen = f.decrypt(b"du")
        # decryptedPasswordDB = passwordChosen.decode('utf-8')
        # print(decryptedPasswordDB)
        user = auth.authenticate(password=password,username=username)
        # selected_field = username
        # print(selected_field)
        print(user)
        if user is not None:
            # data=User.objects.get(username=selected_field);
            # print(data)
            for group in user.groups.all():
                if group.name ==  'principal_investigator':
                    auth.login(request,user)
                    return redirect('/after_login/')
                if group.name ==  'project_manager':
                    auth.login(request,user)
                    return redirect('/after_login/')
                if group.name ==  'nutrition_expert':
                    auth.login(request,user)
                    return redirect('/after_login/')
                if group.name ==  'webgis_expert':
                    auth.login(request,user)
                    return redirect('/after_login/')
                if group.name ==  'mentor':
                    auth.login(request,user)
                    return redirect('/after_login/')
                if group.name ==  'school_coordinator':
                    auth.login(request,user)
                    return redirect('/after_login/')
                if group.name ==  'parents':
                    auth.login(request,user)
                    return redirect('/after_login/')
                if group.name ==  'student':
                    auth.login(request,user)
                    profile=studentprof()
                    return redirect('/after_login/',{'profile':profile})

                if group.name ==  'anganwadi_worker':
                    auth.login(request,user)
                    return redirect('/after_login/')
                if group.name ==  'mukhya_sevika':
                    auth.login(request,user)
                    return redirect('/after_login/')
                if group.name ==  'icds_beneficiaries':
                    auth.login(request,user)
                    return redirect('/after_login/')
                if group.name ==  'nutrigarden_expert':
                    auth.login(request,user)
                    return redirect('/after_login/')
                # if group.name ==  'after_login':
                if group.name ==  'anemic_pregnant_woman':
                    auth.login(request,user)
                    profile=()
                    return redirect('/after_login/',{'profile':profile})
                if group.name ==  'adolescent_girl':
                    auth.login(request,user)
                    profile=anemicadolescentgirlprof()
                    return redirect('/after_login/',{'profile':profile})
                if group.name ==  'anemic_lactating_mother':
                    auth.login(request,user)
                    profile=anemiclactatingmotherprof()
                    return redirect('/after_login/',{'profile':profile})
                if group.name ==  'sam_mam_parents':
                    auth.login(request,user)
                    profile=anemiclactatingmotherprof()
                    return redirect('/after_login/',{'profile':profile})
                   
            
        else:
            messages.info(request,'invalid credentials')
            return redirect('login')
    else:
        return render(request, 'login.html')
    
def logout(request):
    auth.logout(request)
    return redirect("/")


def student_login(request):
    return render(request,'new.html')


def redirectd(request,username):
        print(username)
        selected_field=username
        print(selected_field)
        data=User.objects.get(username=selected_field)
        print(data.groups.all())
        role =data.groups.all()
        print(role)
        for group in data.groups.all():
                if group.name ==  'principal_investigator':
                    return redirect('/after_login/')
                if group.name ==  'project_manager':
                    return redirect('/after_login/')
                if group.name ==  'nutrition_expert':
                    return redirect('/after_login/')
                if group.name ==  'webgis_expert':
                    return redirect('/after_login/')
                if group.name ==  'mentor':
                    return redirect('/after_login/')
                if group.name ==  'school_coordinator':
                    return redirect('/after_login/')
                if group.name ==  'parents':
                    return redirect('/after_login/')
                if group.name ==  'student':
                    return redirect('/after_login/')
                if group.name ==  'anganwadi_worker':
                    return redirect('/after_login/')
                if group.name ==  'mukhya_sevika':
                    return redirect('/after_login/')
                if group.name ==  'icds_beneficiaries':
                    return redirect('/after_login/')
                if group.name ==  'nutrigarden_expert':
                    return redirect('/after_login/')
                if group.name ==  'anemic_pregnant_woman':
                    return redirect('/after_login/')
                if group.name ==  'adolescent_girl':
                    return redirect('/after_login/')
                if group.name ==  'anemic_lactating_mother':
                    return redirect('/after_login/')
                if group.name ==  'sam_mam_parents':
                    return redirect('/after_login/')



def after_login(request):
    # profile_form= SchoolCoordinatorForm()
    # stu_form=StudentForm()
    data= User.objects.all()
    return render(request, 'after_login copy.html',{'data':data})

Diet/templates/article_icds.html
{% extends 'base.html' %} {% load static%}{% block content %} {% load bootstrap4 %}  {% bootstrap_css %}  {% bootstrap_javascript jquery='full' %} 


<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Registration</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

<style>
    .myform {
        margin-top: 200px;
        margin-left: 20%;
        margin-right: 20%;
    }
    
    h1 {
        text-align: center;
        color: rgb(36, 36, 68);
        font-weight: bolder;
    }
</style>
<form action="/student_register/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="myform">
        <h1> Student  Add Info</h1>
        <table>{{profile_form.as_table}}</table>
        <button type="submit" class="btn btn-info">Submit</button>
        <br>
        <br>
        <!-- <span>New User?</span>
        <a href="/register/">Create new account</a> -->
    </div>
</form>


<div>
    {% for message in messages %}
    <h3>{{message}}</h3>{% endfor %}

</div>
<script>
    $(document).ready(function() {
            var val_uid='{{data.student.uid}}';

            $('#id_uid').val(val_uid);
            
        });

</script>
{% endblock %}

Diet/templates/article_nutri.html
{% extends 'base.html' %} {% load static%} {% block content %} {% load crispy_forms_tags %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Minimal Django File Upload Example</title>
    <style>
        .myform {
            margin-top: 200px;
            margin-left: 20%;
            margin-right: 20%;
        }
        
        h1 {
            text-align: center;
            color: rgb(11, 11, 36);
            font-weight: bolder;
        }
    </style>
</head>

<body class="myform">
    <!-- List of uploaded documents -->
    <h1>Articles</h1>
    {% if document %}
    <ul>
        {% for doc in document %}
        <li>
            <h5>{{doc.title}}</h5>
        </li>

        <a href="{{ doc.document.url }}">View/Download</a> {% endfor %}
    </ul>
    {% else %}
    <p>No documents.</p>
    {% endif %}
    <h1>Images</h1>
    {% if image %}
    <ul>
        {% for img in image %}
        <li>
            <h5>{{img.title}}</h5>
        </li>

        <a href="{{ img.image.url }}">View/Download</a> {% endfor %}
    </ul>
    {% else %}
    <p>No Images.</p>
    {% endif %}

    <h1>Videos</h1>
    {% if video %}
    <ul>
        {% for vid in video %}
        <li>
            <h5>{{vid.title}}</h5>
        </li>

        <a href="{{ vid.video.url }}">View/Download</a> {% endfor %}
    </ul>
    {% else %}
    <p>No Videos.</p>
    {% endif %}
  
</body>
<script>
    console.log("{{ document.docfile.name }}")
</script>

</html>{% endblock %}

Diet/templates/bulk_reg_ms.html
{% extends 'base.html' %} {% load static%} {% block content %}
<style>
    .myform {
        margin-top: 200px;
        margin-left: 20px;
        margin-right: 20px;
        text-align: center;
    }
    
    h1 {
        text-align: center;
    }
</style>





<form method="post" enctype="multipart/form-data" class="myform">
    {% csrf_token %}
    <h1>Bulk registration for Mukhya Sevika</h1>
        <a href="{% static 'xlsxforms/Mukhya_Sevika_File.xlsx' %}" target="_blank">Download Mukhya Sevika Sample File</a>
    <br>
    <span>Please Upload Excel(.xlsx) File</span>
    <br>
    <br>
    <input type="file" name="myFile"> <br> <br>
    <button type="submit" class="btn btn-info">Upload file</button>
</form>
{% if messages %} {% for message in messages %}
<div class="alert alert-{{ message.tags }}" UserRole="alert">
    <p {% if message.tags %} class="" {% endif %}>{{ message }}</p>
</div>{% endfor %} {% endif %}
<!--   -->
{% endblock %}

Diet/templates/feedback_form.html
{% extends 'base.html' %} {% load static%} {% block content %} {% load crispy_forms_tags %}{% load wagtailcore_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Body Form</title>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <style>
        /* body {
            margin-top: 100px;
            background: aliceblue;
        }
        
        form {
            margin: auto;
            width: 85%;
            box-shadow: 5px 10px #bdbcbc;
            border-radius: 10px;
            padding: 40px 40px 40px 40px;
            border-style: solid;
            border-color: rgb(190, 186, 186);
            margin-top: 100px;
            color: #403300;
            align-items: center;
        } */
        
        form span {
            color: red;
            font-size: 15px;
        }
        /*         
        h1 {
            background-color: #066f95;
            padding: 20px 20px 20px 20px;
            border-radius: 10px;
            text-align: center;
            color: white;
            font-weight: bolder;
            padding-bottom: 10px;
        } */
        
        .button {
            width: 20%;
            display: inline-block;
            padding: 15px 25px;
            font-size: 24px;
            cursor: pointer;
            text-align: center;
            text-decoration: none;
            outline: none;
            color: #fff;
            background-color: #066f95;
            border: none;
            border-radius: 15px;
            box-shadow: 0 5px #999;
        }
        
        .button:hover {
            background-color: #568088
        }
        
        #map {
            width: 1000px;
            height: 600px;
        }
        
        .button:active {
            background-color: #55a5b5;
            box-shadow: 0 5px #666;
            transform: translateY(4px);
        }
        
        h2 {
            padding-bottom: 10px;
            padding-top: 10px;
            color: #066f95;
            text-decoration: underline;
            font-weight: 400;
            text-align: center;
        }
        
        h3 {
            padding-top: 20px;
        }
        
        label {
            font-weight: bold;
            font-size: 20px;
            color: black;
        }
        
        #calculate {
            cursor: pointer;
            text-align: center;
            width: 200px;
            padding: 5px;
            margin: 10px;
            margin-left: auto;
            margin-right: auto;
            border: 1px solid #999;
            border-radius: 10px;
            background: rgb(245, 243, 243);
            background: -moz-linear-gradient(top, #FFD119, #E6B800);
            font-weight: bold;
            height: 28px;
        }
        
        #calculate:hover {
            background: -webkit-gradient(linear, left top, left bottom, from(#E6B800), to(#FFD119));
            background: -moz-linear-gradient(top, #E6B800, #FFD119);
            margin-top: 13px;
            height: 25px;
        }
        
        #calculate:active {
            background: #403300;
            padding-top: 10px;
            height: 20px;
        }
        
        input,
        select {
            width: 100%;
            color: rgb(39, 22, 22);
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 4px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
    </style>
    </head>

<body>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  
    <div class="english box">
        <form action="" method="POST">
            {% csrf_token %}
            <h2>
               FeedBack
            </h2>
            <table border="0" align="center" cellspacing="10">
                <tr>
                    <td>Name : </td>
                    <td><input type="text" class="fieldlabels" placeholder="Name" style="width: 90%;" name="name" id="name"> </td>
                </tr>
                <tr>
                    <td>Issues : </td>
                    <td><textarea placeholder="Issues" style="width: 90%;" name="issues" id="issues" rows="5" cols="5"></textarea> </td>
               
                <tr>
                    <td>Suggestions : </td>
                    <td><textarea placeholder="Suggestions" style="width: 90%"; name ="suggestions" id = "suggestions" cols="5" rows="5"></textarea></td>
                    
                </tr>

              

            </table>
            <center><input type="submit" value="Submit" class="button"></center>

        </form>
    </div>
   
</body>
<script>
</script>

</html> {% endblock %}

Diet/templates/nutri_anthro_para.html
{% extends 'base.html' %} {% load static%}{% block content %} {% load bootstrap4 %}  {% bootstrap_css %}  {% bootstrap_javascript jquery='full' %} 


<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Registration</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="">

<style>
    .myform {
        margin-top: 200px;
        margin-left: 20%;
        margin-right: 20%;
    }
    
    h1 {
        text-align: center;
        color: rgb(36, 36, 68);
        font-weight: bolder;
    }
</style>

<div class="form-group">

<form action="/nutri_anthropometric_parameters/" method="POST"  enctype="multipart/form-data" >
    {% csrf_token %}

    <div class="myform">
        <h1> Anthropometric Details </h1>
        <!-- <table> {{form.media}} {{form.as_table}} </table> -->
         {{form.media}} {{form.as_p}}
        <button type="submit" class="btn btn-info">Submit</button>
        <br>
        <br>
        <!-- <span>New User?</span>
        <a href="/register/">Create new account</a> -->
    </div>
</form>

</div>

<div>
    {% for message in messages %}
    <h3>{{message}}</h3>{% endfor %}

</div>
<script>

</script>

{% endblock %}

Diet/templates/nutri_info.html
{% extends 'base.html' %} {% load static%}{% block content %} {% load bootstrap4 %}  {% bootstrap_css %}  {% bootstrap_javascript jquery='full' %} 


<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Registration</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="">

<style>
    .myform {
        margin-top: 200px;
        margin-left: 20%;
        margin-right: 20%;
    }
    
    h1 {
        text-align: center;
        color: rgb(36, 36, 68);
        font-weight: bolder;
    }
</style>

<form action="/nutri_infotainment_survey/" method="POST"  enctype="multipart/form-data" >
    {% csrf_token %}

    <div class="myform">
        <h1> General Information Survey </h1>
        <table> {{form.media}} {{form.as_table}} </table>
        <button type="submit" class="btn btn-info">Submit</button>
        <br>
        <br>
        <!-- <span>New User?</span>
        <a href="/register/">Create new account</a> -->
    </div>
</form>

<div>
    {% for message in messages %}
    <h3>{{message}}</h3>{% endfor %}

</div>
<script>
  $(document).ready(function() {
        $(".some_class").change(function() {
            var mdate = $("#id_birthdate").val().toString();
            console.log(mdate)
            var yearThen = parseInt(mdate.substring(0, 4), 10);
            var monthThen = parseInt(mdate.substring(5, 7), 10);
            var dayThen = parseInt(mdate.substring(8, 10), 10);

            var today = new Date();
            var birthday = new Date(yearThen, monthThen - 1, dayThen);

            var differenceInMilisecond = today.valueOf() - birthday.valueOf();

            var year_age = Math.floor(differenceInMilisecond / 31536000000);
            console.log(year_age)
            var day_age = Math.floor((differenceInMilisecond % 31536000000) / 86400000);

            if ((today.getMonth() == birthday.getMonth()) && (today.getDate() == birthday.getDate())) {
                alert("Happy B'day!!!");
            }

            var month_age = Math.floor(day_age / 30);



            $('#id_age').val(year_age+'years'+month_age+'months'+day_age+'days');
            
        });
    });
</script>

{% endblock %}

Diet/templates/video_nutri.html
{% extends 'base.html' %} {% load static%} {% block content %} {% load crispy_forms_tags %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Minimal Django File Upload Example</title>
    <style>
        .myform {
            margin-top: 200px;
            margin-left: 20%;
            margin-right: 20%;
        }
        
        h1 {
            text-align: center;
            color:black;
        }
    </style>
</head>

<body class="myform">
    <form action="{% url 'video_nutri' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Upload video for Nutri Garden project</h1>
      
        {{ form|crispy }}
        <p><button type="submit" class="btn btn-info"> Upload</button></p>
    </form>
</body>

</html>{% endblock %}